[tool.poetry]
name = "corallab-sim"
version = "0.1.0"
description = ""
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
readme = "README.org"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"
pybullet = "^3.2.5"
scikit-learn = "^1.3.2"
ur-rtde = {path = "../ur_rtde", develop = false}
mujoco = "^3.0.1"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
