[tool.poetry]
name = "corallab-sim"
version = "0.1.0"
description = ""
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
readme = "README.org"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
numpy = "<1.24"
scikit-learn = "^1.3.2"
corallab-assets = {path = "../corallab-assets", develop = true}

[tool.poetry.group.reality]
optional = true

[tool.poetry.group.reality.dependencies]
ur-rtde = {path = "../ur_rtde"}

[tool.poetry.group.pybullet]
optional = true

[tool.poetry.group.pybullet.dependencies]
pybullet = "^3.2.5"

[tool.poetry.group.mujoco]
optional = true

[tool.poetry.group.mujoco.dependencies]
mujoco = "^3.0.1"

[tool.poetry.group.torch_robotics]
optional = true

[tool.poetry.group.torch_robotics.dependencies]
torch-robotics = {path = "../torch_robotics", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
