[project]
name = "corallab-lib"
version = "0.1.0"
description = "Library providing a common API to many useful robotics libraries."
authors = [{name = "Tassos Manganaris", email = "tassos.manganaris@gmail.com"}]
requires-python = ">=3.8,<3.9"
dependencies = ["corallab-assets @ git+https://github.com/corallab-base/assets.git@0.2.2", "pygame", "gymnasium"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# Tasks

[tool.pixi.tasks]

# Dependencies

[tool.pixi.dependencies]
python = "3.8.*"
numpy = "<1.24"

[project.optional-dependencies]
pybullet = ["pybullet", "pybullet-envs-gymnasium"]
torch-robotics = ["torch-robotics @ file:///home/tassos/phd/qureshi/first-project/torch_robotics"]

[tool.pixi.pypi-dependencies]
corallab-lib = { path = ".", editable = true }

# Environments

[tool.pixi.environments]
default = {features = ["pybullet", "torch-robotics"], solve-group = "default"}
