[tool.poetry]
name = "corallab-lib"
version = "0.1.0"
description = ""
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
readme = "README.org"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
numpy = "<1.24"
scikit-learn = "^1.3.2"
corallab-assets = {git = "https://github.com/corallab-base/assets.git", rev = "0.2.2"}

pybullet = { version = "^3.2.5", optional = true }
pybullet-envs-gymnasium = {git = "https://github.com/araffin/pybullet_envs_gymnasium", optional = true }

mujoco = { version = "^3.0.1", optional = true }
torch-robotics = {path = "../torch_robotics", optional = true, develop = true}

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"


[tool.poetry.extras]
pybullet = ["pybullet", "pybullet-envs-gymnasium"]
torch-robotics = ["torch-robotics"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
